import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { RecordsAPI } from "../services/api";
import Card from "../components/ui/Card";
import Button from "../components/ui/Button";
import { currency } from "../utils/currency";

export default function RecordDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [record, setRecord] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const data = await RecordsAPI.get(id);
        setRecord(data);
      } catch (err) {
        console.error("Failed to fetch record:", err);
      } finally {
        setLoading(false);
      }
    })();
  }, [id]);

  if (loading) return <div className="p-4">Loading record details...</div>;
  if (!record) return <div className="p-4">Record not found.</div>;

  const profit =
    Number(record.sellingPrice || 0) -
    Number(record.buyingPrice || 0) -
    Number(record.expenses || 0);

  return (
    <div className="p-4 space-y-6 dark:text-slate-100 print:p-0">
      {/* Toolbar (hidden when printing) */}
      <div className="flex justify-between items-center mb-4 print:hidden">
        <Button variant="outline" onClick={() => navigate(-1)}>
          ← Back to Records
        </Button>
        <Button variant="primary" onClick={() => window.print()}>
          🖨️ Print Record
        </Button>
      </div>

      {/* Printable Report */}
      <div
        className="bg-white dark:bg-slate-800 rounded-xl shadow p-8 print:shadow-none print:bg-white print:dark:bg-white"
        style={{ maxWidth: "800px", margin: "auto" }}
      >
        {/* Header */}
        <div className="flex justify-between items-center border-b pb-4 mb-6 print:border-black/20">
          <div>
            <h1 className="text-2xl font-bold text-slate-800 dark:text-slate-900">
              Agency Finance Report
            </h1>
            <p className="text-slate-500 text-sm">Transaction Record Summary</p>
          </div>
          <img
            src="/logo.png"
            alt="Agency Logo"
            className="h-12 w-auto print:filter-none dark:invert"
            onError={(e) => (e.target.style.display = "none")}
          />
        </div>

        {/* Record Info */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
          <Detail label="Customer" value={record.customerName} />
          <Detail label="Service Type" value={record.typeOfService} />
          <Detail label="Selling Price" value={currency(record.sellingPrice)} />
          <Detail label="Buying Price" value={currency(record.buyingPrice)} />
          <Detail label="Expenses" value={currency(record.expenses)} />
          <Detail label="Commission" value={currency(record.commission)} />
          <Detail label="Profit" value={currency(profit)} />
          <Detail
            label="Created By"
            value={record.createdBy?.name || record.createdBy}
          />
          <Detail
            label="Created At"
            value={new Date(record.createdAt).toLocaleString()}
          />
        </div>

        {/* Footer */}
        <div className="mt-10 border-t pt-4 text-center text-xs text-slate-500 print:border-black/20">
          <p>
            Generated by <b></b> — {new Date().toLocaleDateString()}
          </p>
          <p>© {new Date().getFullYear()} All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}

function Detail({ label, value }) {
  return (
    <div className="flex flex-col border-b border-slate-200 dark:border-slate-700 pb-2 print:border-black/20">
      <span className="text-xs text-slate-500">{label}</span>
      <span className="font-medium text-slate-800 dark:text-slate-900">
        {value ?? "—"}
      </span>
    </div>
  );
}
